import type { AppRepository } from "./AppRepository";
import {
  createPreparationSession,
  createTodayOnlyTemporaryItem,
  defaultChildProfile,
  loadChildProfile,
  loadCheckCounts,
  loadCustomItems,
  loadPreparationSession,
  loadSpotAdditions,
  loadSpotDeadlines,
  loadTodayOnlyTemporaryItems,
  saveCheckCounts,
  saveChildProfile,
  saveCustomItems,
  savePreparationSession,
  saveSpotAdditions,
  saveSpotDeadlines,
  saveTodayOnlyTemporaryItems,
} from "../storage";

export const localRepository: AppRepository = {
  defaultChildProfile,
  loadPreparationSession,
  savePreparationSession,
  loadCheckCounts,
  saveCheckCounts,
  loadCustomItems,
  saveCustomItems,
  loadTodayOnlyTemporaryItems,
  saveTodayOnlyTemporaryItems,
  loadSpotAdditions,
  saveSpotAdditions,
  loadSpotDeadlines,
  saveSpotDeadlines,
  loadChildProfile,
  saveChildProfile,
  createTodayOnlyTemporaryItem,
  createPreparationSession,
};
